---

- name: Install the IIS web service
  hosts: windows
  vars:
    iis_sites:
      - name: 'Ansible Playbook Test'
        port: '8080'
        path: 'C:\sites\playbooktest'
      - name: 'Ansible Playbook Test 2'
        port: '8081'
        path: 'C:\sites\playbooktest2'
    iis_test_message: "Hello World. This is my Red Hat IIS test server demo."

  tasks:

    - name: Install IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present

    - name: Create site directory structure
      with_items: "{{ iis_sites }}"
      ansible.windows.win_file:
        path: "{{ item.path }}"
        state: directory

    - name: Create IIS site
      with_items: "{{ iis_sites }}"
      notify: Restart IIS Service
      community.windows.win_iis_website:
        name: "{{ item.name }}"
        state: started
        port: "{{ item.port }}"
        physical_path: "{{ item.path }}"

    - name: Open port for site on the firewall
      with_items: "{{ iis_sites }}"
      community.windows.win_firewall_rule:
        name: "iisport{{ item.port }}"
        enable: true
        state: present
        localport: "{{ item.port }}"
        action: Allow
        direction: In
        protocol: TCP

    - name: Template simple web site to iis_site_path as index.html
      with_items: "{{ iis_sites }}"
      ansible.windows.win_template:
        src: 'index.html.j2'
        dest: '{{ item.path }}\index.html'

    - name: Show website addresses
      loop:
        - http://{{ ansible_host }}:8080
        - http://{{ ansible_host }}:8081
      ansible.builtin.debug:
        msg: "{{ item }}"

  handlers:
    - name: Restart IIS Service
      ansible.windows.win_service:
        name: W3Svc
        state: restarted
        start_mode: auto
