---

- name: Change the Cisco banners
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        state: present
        text: "{{ network_banner }}"

    - name: Configure the MOTD
      cisco.ios.ios_banner:
        banner: login
        state: present
        text: |
          This is my MOTD banner
          that contains a multiline
          string managed by Ansible.
